image: node:latest

stages:
    - build
    - test
    - deploy

build_frontend:
    stage: build
    script:
        - echo "trying frontend build in gitlab-ci.yml"
        - cd frontend
        - npm install
        - CI=false npm run-script build

# Credit: https://gitlab.com/JohnPowow/animalwatch/-/blob/main/.gitlab-ci.yml
test_jest:
    stage: test
    image: node:latest
    script:
        - echo "trying jest tests"
        - cd frontend
        - npm install npm@8.5.5 -g
        - npm install
        - npm run test

deploy_frontend:
    stage: deploy
    script:
        - echo "nothing implemented for deploy_frontend yet in gitlab-ci.yml"
